(function () {
  'use strict';

  const I18N = {
    fr: {
      eyebrow: "Authentificateur local",
      lead: "Tes codes à double authentification restent dans un coffre chiffré sur ton téléphone. Aucun compte Heimdguard, aucun cloud obligatoire, aucun serveur BarbareDestroy.",
      privacyLine: "Conçu pour fonctionner hors ligne : ajout par QR code ou clé secrète, génération TOTP, sauvegarde chiffrée et restauration locale.",
      badge1: "Hors ligne", badge2: "Coffre chiffré", badge3: "Sans publicité", badge4: "Sans compte",
      storeSoon: "Lien de l'application à venir", mockLocal: "Local • hors ligne • chiffré", mockAdd: "+ Ajouter une clé",
      featuresA: "Tes clés. Ton appareil.", featuresB: "Heimdguard fait une seule chose : générer tes codes d'authentification sans confier tes secrets à un serveur BarbareDestroy.",
      f1t: "TOTP standard", f1d: "Compatible avec les services utilisant le standard TOTP et les liens otpauth://.",
      f2t: "Coffre chiffré local", f2d: "Les secrets sont stockés chiffrés sur l'appareil et protégés par Android Keystore.",
      f3t: "QR code ou saisie manuelle", f3d: "Scanne le QR fourni par le service ou ajoute directement une clé secrète Base32.",
      f4t: "PIN facultatif", f4d: "Ajoute une protection locale supplémentaire si tu le souhaites, sans rendre le PIN obligatoire.",
      f5t: "Sauvegarde chiffrée", f5d: "Crée une sauvegarde locale protégée par une phrase de passe d'au moins 23 caractères et conserve-la où tu veux.",
      f6t: "Aucune collecte", f6d: "Pas de compte Heimdguard, pas de publicité, pas d'analyse d'audience et aucune base distante de tes clés.",
      manifestTitle: "Pas de serveur pour récupérer tes clés. C'est volontaire.",
      manifestText: "Heimdguard privilégie la maîtrise locale. Si ton téléphone est perdu, cassé ou réinitialisé, BarbareDestroy ne possède aucune copie permettant de restaurer ton coffre. Une sauvegarde chiffrée réalisée par l'utilisateur est donc essentielle.",
      s1t: "Ajoute", s1d: "Scanne le QR code ou saisis la clé secrète fournie par ton service.",
      s2t: "Protège", s2d: "Active un PIN local si tu le souhaites et garde ton téléphone verrouillé.",
      s3t: "Sauvegarde", s3d: "Exporte rapidement une sauvegarde chiffrée vers un support que tu contrôles.",
      available: "Bientôt sur Google Play", downloadTitle: "Télécharger Heimdguard", downloadIntro: "Le lien sera remplacé par la fiche Heimdguard dès sa publication.", android: "Pour Android",
      navHome: "Accueil BarbareDestroy", navPrivacy: "Politique de confidentialité", navTerms: "Conditions d'utilisation",
      privacyTitle: "Politique de confidentialité", privacyIntro: "Dernière mise à jour : 20 septembre 2026",
      p1t: "1. Responsable et application concernée", p1d: "Heimdguard est une application Android gratuite éditée par Serge Hinzelin sous le nom BarbareDestroy. Elle permet de stocker localement des secrets d'authentification et de générer des codes TOTP temporaires.",
      p2t: "2. Aucun compte et aucune base distante", p2d: "Heimdguard ne demande aucun compte BarbareDestroy et n'utilise aucun serveur BarbareDestroy pour stocker ou synchroniser les clés TOTP. BarbareDestroy ne reçoit aucune copie de tes secrets, codes, sauvegardes ou listes de comptes.",
      p3t: "3. Données conservées localement", p3d: "Le coffre peut contenir le nom du service, la clé secrète TOTP et les paramètres techniques nécessaires à la génération du code. Les préférences de thème, langue, tutoriel et sécurité sont également conservées localement sur l'appareil.",
      p4t: "4. Chiffrement et Android Keystore", p4d: "Les secrets du coffre sont chiffrés localement. Heimdguard utilise les mécanismes de sécurité Android, notamment Android Keystore, afin que la clé de chiffrement de l'application ne soit pas stockée comme un simple texte exportable avec la base.",
      p5t: "5. Caméra et QR codes", p5d: "La caméra est sollicitée uniquement lorsque l'utilisateur choisit de scanner un QR code d'authentification. Les images servent à lire le QR sur l'appareil ; elles ne sont ni envoyées à BarbareDestroy ni conservées comme photos.",
      p6t: "6. Presse-papiers", p6d: "Lorsque l'utilisateur copie un code, celui-ci est placé dans le presse-papiers Android. Son traitement ultérieur dépend du système, du clavier et des fonctions installées sur l'appareil. Heimdguard n'envoie pas ce contenu à BarbareDestroy.",
      p7t: "7. Sauvegardes locales chiffrées", p7d: "Heimdguard permet de créer un fichier de sauvegarde chiffré protégé par une phrase de passe d'au moins 23 caractères. L'utilisateur choisit où conserver ce fichier. BarbareDestroy n'en reçoit aucune copie et ne peut récupérer ni une sauvegarde perdue ni son mot de passe.",
      p8t: "8. Pas de sauvegarde cloud automatique du coffre", p8d: "Le coffre Heimdguard n'est pas destiné à être sauvegardé automatiquement par les mécanismes de sauvegarde Android. Une sauvegarde exportée volontairement reste sous la responsabilité de l'utilisateur et peut être placée sur un disque, une clé USB ou un service cloud de son choix.",
      p9t: "9. Réseau, publicité et analyse", p9d: "Le fonctionnement de Heimdguard est conçu pour rester local. L'application n'intègre ni publicité, ni SDK publicitaire, ni analyse d'audience, ni profilage et ne nécessite aucun serveur BarbareDestroy pour générer les codes TOTP.",
      p10t: "10. Suppression et durée de conservation", p10d: "Les données du coffre restent sur l'appareil jusqu'à leur suppression dans l'application, l'effacement des données Android ou la désinstallation. Les sauvegardes exportées hors de l'application ne sont pas supprimées automatiquement et doivent être supprimées par l'utilisateur à leur emplacement.",
      p11t: "11. Téléphone perdu, cassé ou volé", p11d: "Heimdguard ne possède aucun mécanisme de récupération distante des clés par BarbareDestroy. En cas de perte, panne, vol ou réinitialisation, la récupération dépend de la sauvegarde chiffrée conservée par l'utilisateur et des procédures de récupération proposées par chaque service protégé.",
      p12t: "12. Google Play et services tiers", p12d: "Google Play peut traiter des données selon ses propres règles pour le téléchargement, les mises à jour ou la sécurité du Store. Ces traitements sont distincts du fonctionnement local de Heimdguard. Les services pour lesquels des codes sont générés appliquent également leurs propres politiques.",
      p13t: "13. Droits et contact", p13d: "BarbareDestroy ne disposant pas d'une base distante des clés Heimdguard, la suppression des données locales s'effectue directement sur l'appareil. Pour toute question relative à la confidentialité, contacte l'éditeur depuis barbaredestroy.fr. Une réclamation peut également être adressée à la CNIL lorsqu'elle est compétente.",
      p14t: "14. Modification de cette politique", p14d: "Cette politique peut évoluer si les fonctions de Heimdguard ou les obligations légales changent. La date affichée en haut de la page indique la dernière révision.",
      p15t: "15. Mineurs", p15d: "Heimdguard ne demande pas l’âge de ses utilisateurs et n’est pas conçu pour collecter des données personnelles concernant des mineurs. Le fonctionnement du coffre reste local sur l’appareil.",
      termsTitle: "Conditions d'utilisation", termsIntro: "Dernière mise à jour : 20 septembre 2026 — En installant ou en utilisant Heimdguard, l'utilisateur accepte les présentes conditions.",
      t1t: "1. Éditeur et objet", t1d: "Heimdguard est une application Android gratuite éditée par Serge Hinzelin sous le nom BarbareDestroy. Elle sert à enregistrer localement des secrets d'authentification et à générer des codes TOTP.",
      t2t: "2. Utilisation personnelle", t2d: "Une licence personnelle, gratuite, non exclusive et révocable est accordée pour utiliser Heimdguard conformément à sa fonction. L'application ne doit pas être utilisée pour contourner la sécurité d'un compte auquel l'utilisateur n'est pas autorisé à accéder.",
      t3t: "3. Responsabilité de sauvegarde", t3d: "Heimdguard ne conserve aucune copie distante permettant à BarbareDestroy de restaurer les clés. L'utilisateur est responsable de créer et conserver une sauvegarde chiffrée exploitable et de garder disponibles les méthodes de récupération proposées par les services protégés.",
      t4t: "4. Compatibilité TOTP et heure de l'appareil", t4d: "La génération des codes dépend du standard TOTP, des paramètres fournis par le service et de l'heure correcte de l'appareil. BarbareDestroy ne garantit pas la compatibilité avec tous les services présents ou futurs ni avec les modifications décidées par des tiers.",
      t5t: "5. Sécurité", t5d: "Heimdguard met en œuvre des protections locales, mais aucun logiciel ne peut garantir une sécurité absolue sur un appareil compromis. L'utilisateur doit protéger son téléphone, installer les mises à jour de sécurité Android et éviter de communiquer ses clés secrètes ou sauvegardes.",
      t6t: "6. Sauvegardes et mot de passe", t6d: "Les sauvegardes sont protégées par une phrase de passe définie par l'utilisateur. BarbareDestroy ne connaît pas cette phrase et ne peut pas la réinitialiser. La perte du téléphone, de la sauvegarde ou de son mot de passe peut rendre la restauration impossible.",
      t7t: "7. Services tiers", t7d: "Heimdguard est indépendant des services pour lesquels des codes sont générés. Les noms de services éventuellement affichés restent la propriété de leurs titulaires. Leur fonctionnement, disponibilité et procédures de récupération relèvent de leurs éditeurs respectifs.",
      t8t: "8. Confidentialité", t8d: "Le fonctionnement local, les données traitées et les modalités de suppression sont détaillés dans la politique de confidentialité de Heimdguard.",
      t9t: "9. Propriété intellectuelle", t9d: "Le nom Heimdguard, le logo, l'interface et les éléments graphiques propres à l'application restent la propriété de Serge Hinzelin, sous réserve des composants tiers et de leurs licences.",
      t10t: "10. Évolution de l'application", t10d: "Les fonctions, l'interface et les présentes conditions peuvent évoluer. L'utilisateur peut cesser d'utiliser Heimdguard et le désinstaller à tout moment.",
      t11t: "11. Limitation de responsabilité", t11d: "Dans les limites autorisées par la loi, l'éditeur ne peut être tenu responsable d'une perte d'accès à un service, d'une sauvegarde inutilisable, d'un appareil perdu ou compromis, ou d'un changement imposé par un service tiers. Les droits impératifs du consommateur restent applicables.",
      t12t: "12. Droit applicable et contact", t12d: "Le droit français s'applique sans priver le consommateur des protections impératives de son pays de résidence. Pour toute question, contacte l'éditeur depuis barbaredestroy.fr."
    },
    en: {
      eyebrow: "Local authenticator",
      lead: "Your two-factor authentication codes stay in an encrypted vault on your phone. No Heimdguard account, no mandatory cloud and no BarbareDestroy server.",
      privacyLine: "Designed to work offline: add accounts by QR code or secret key, generate TOTP codes, create encrypted backups and restore locally.",
      badge1: "Offline", badge2: "Encrypted vault", badge3: "No ads", badge4: "No account",
      storeSoon: "App listing link coming soon", mockLocal: "Local • offline • encrypted", mockAdd: "+ Add a key",
      featuresA: "Your keys. Your device.", featuresB: "Heimdguard does one thing: generate authentication codes without entrusting your secrets to a BarbareDestroy server.",
      f1t: "Standard TOTP", f1d: "Compatible with services using the TOTP standard and otpauth:// links.",
      f2t: "Local encrypted vault", f2d: "Secrets are encrypted on the device and protected with Android Keystore.",
      f3t: "QR code or manual entry", f3d: "Scan the QR code supplied by the service or enter a Base32 secret key directly.",
      f4t: "Optional PIN", f4d: "Add extra local protection if you want it, without making a PIN mandatory.",
      f5t: "Encrypted backup", f5d: "Create a local backup protected by a passphrase of at least 23 characters and store it wherever you choose.",
      f6t: "No collection", f6d: "No Heimdguard account, no ads, no audience analytics and no remote database containing your keys.",
      manifestTitle: "No server can recover your keys. That's intentional.", manifestText: "Heimdguard puts local control first. If your phone is lost, broken or reset, BarbareDestroy has no copy that can restore your vault. An encrypted backup made by the user is therefore essential.",
      s1t: "Add", s1d: "Scan the QR code or enter the secret key supplied by your service.", s2t: "Protect", s2d: "Enable a local PIN if you want one and keep your phone locked.", s3t: "Back up", s3d: "Export an encrypted backup to storage you control.",
      available: "Coming soon to Google Play", downloadTitle: "Download Heimdguard", downloadIntro: "This link will be replaced with the Heimdguard listing as soon as it is published.", android: "For Android",
      navHome: "BarbareDestroy home", navPrivacy: "Privacy policy", navTerms: "Terms of use",
      privacyTitle: "Privacy policy", privacyIntro: "Last updated: September 20, 2026",
      p1t: "1. Publisher and covered application", p1d: "Heimdguard is a free Android application published by Serge Hinzelin under the BarbareDestroy name. It stores authentication secrets locally and generates temporary TOTP codes.",
      p2t: "2. No account and no remote database", p2d: "Heimdguard requires no BarbareDestroy account and uses no BarbareDestroy server to store or synchronize TOTP keys. BarbareDestroy receives no copy of your secrets, codes, backups or account list.",
      p3t: "3. Data kept locally", p3d: "The vault may contain the service name, TOTP secret and technical parameters required to generate codes. Theme, language, tutorial and security preferences are also stored locally on the device.",
      p4t: "4. Encryption and Android Keystore", p4d: "Vault secrets are encrypted locally. Heimdguard uses Android security mechanisms, including Android Keystore, so the application's encryption key is not stored as simple exportable text alongside the database.",
      p5t: "5. Camera and QR codes", p5d: "The camera is requested only when the user chooses to scan an authentication QR code. Images are used to read the QR code on the device; they are neither sent to BarbareDestroy nor kept as photos.",
      p6t: "6. Clipboard", p6d: "When the user copies a code, it is placed in the Android clipboard. Its subsequent handling depends on the operating system, keyboard and features installed on the device. Heimdguard does not send this content to BarbareDestroy.",
      p7t: "7. Encrypted local backups", p7d: "Heimdguard can create an encrypted backup protected by a passphrase of at least 23 characters. The user chooses where to keep the file. BarbareDestroy receives no copy and cannot recover a lost backup or its password.",
      p8t: "8. No automatic cloud backup of the vault", p8d: "The Heimdguard vault is not intended to be backed up automatically through Android backup mechanisms. A backup deliberately exported by the user remains under the user's responsibility and may be placed on a drive, USB storage or cloud service of their choice.",
      p9t: "9. Network, advertising and analytics", p9d: "Heimdguard is designed to operate locally. The application includes no advertising, advertising SDK, audience analytics or profiling, and requires no BarbareDestroy server to generate TOTP codes.",
      p10t: "10. Deletion and retention", p10d: "Vault data stays on the device until it is deleted in the application, Android app data is cleared, or the app is uninstalled. Backups exported outside the app are not deleted automatically and must be removed by the user from their storage location.",
      p11t: "11. Lost, broken or stolen phone", p11d: "Heimdguard has no BarbareDestroy remote key-recovery mechanism. If a phone is lost, broken, stolen or reset, recovery depends on the encrypted backup kept by the user and the recovery procedures offered by each protected service.",
      p12t: "12. Google Play and third-party services", p12d: "Google Play may process data under its own rules for downloads, updates or Store security. Those operations are separate from Heimdguard's local operation. Services for which codes are generated also apply their own policies.",
      p13t: "13. Rights and contact", p13d: "Because BarbareDestroy has no remote database of Heimdguard keys, local data is deleted directly on the device. For privacy questions, contact the publisher through barbaredestroy.fr. A complaint may also be submitted to the CNIL where it is competent.",
      p14t: "14. Changes to this policy", p14d: "This policy may change if Heimdguard features or legal requirements change. The date shown at the top of the page indicates the latest revision.",
      p15t: "15. Minors", p15d: "Heimdguard does not ask users for their age and is not designed to collect personal data about minors. Vault operation remains local to the device.",
      termsTitle: "Terms of use", termsIntro: "Last updated: September 20, 2026 — By installing or using Heimdguard, the user accepts these terms.",
      t1t: "1. Publisher and purpose", t1d: "Heimdguard is a free Android application published by Serge Hinzelin under the BarbareDestroy name. It stores authentication secrets locally and generates TOTP codes.",
      t2t: "2. Personal use", t2d: "A personal, free, non-exclusive and revocable licence is granted to use Heimdguard for its intended purpose. The application must not be used to bypass the security of an account the user is not authorised to access.",
      t3t: "3. Backup responsibility", t3d: "Heimdguard keeps no remote copy that would allow BarbareDestroy to restore keys. The user is responsible for creating and retaining a usable encrypted backup and for keeping the recovery methods provided by protected services available.",
      t4t: "4. TOTP compatibility and device time", t4d: "Code generation depends on the TOTP standard, parameters supplied by the service and correct device time. BarbareDestroy does not guarantee compatibility with every current or future service or with changes made by third parties.",
      t5t: "5. Security", t5d: "Heimdguard implements local protections, but no software can guarantee absolute security on a compromised device. Users should protect their phone, install Android security updates and avoid sharing secret keys or backups.",
      t6t: "6. Backups and password", t6d: "Backups are protected by a passphrase chosen by the user. BarbareDestroy does not know this passphrase and cannot reset it. Losing the phone, backup or its password may make restoration impossible.",
      t7t: "7. Third-party services", t7d: "Heimdguard is independent from the services for which codes are generated. Service names that may be displayed remain the property of their respective owners. Their operation, availability and recovery procedures are controlled by those publishers.",
      t8t: "8. Privacy", t8d: "Local operation, processed data and deletion methods are described in Heimdguard's privacy policy.",
      t9t: "9. Intellectual property", t9d: "The Heimdguard name, logo, interface and original graphic elements remain the property of Serge Hinzelin, subject to third-party components and their licences.",
      t10t: "10. Application changes", t10d: "Features, interface and these terms may evolve. The user may stop using Heimdguard and uninstall it at any time.",
      t11t: "11. Limitation of liability", t11d: "To the extent permitted by law, the publisher cannot be held liable for loss of access to a service, an unusable backup, a lost or compromised device, or changes imposed by a third-party service. Mandatory consumer rights remain applicable.",
      t12t: "12. Governing law and contact", t12d: "French law applies without depriving consumers of mandatory protections in their country of residence. For questions, contact the publisher through barbaredestroy.fr."
    },
    de: {
      eyebrow: "Lokaler Authentifikator", lead: "Deine Zwei-Faktor-Codes bleiben in einem verschlüsselten Tresor auf deinem Smartphone. Kein Heimdguard-Konto, keine Pflicht-Cloud und kein BarbareDestroy-Server.", privacyLine: "Für Offline-Betrieb entwickelt: QR-Code oder geheimer Schlüssel, TOTP-Erzeugung sowie verschlüsselte lokale Sicherung und Wiederherstellung.", badge1: "Offline", badge2: "Verschlüsselter Tresor", badge3: "Ohne Werbung", badge4: "Ohne Konto", storeSoon: "App-Link folgt", mockLocal: "Lokal • offline • verschlüsselt", mockAdd: "+ Schlüssel hinzufügen", featuresA: "Deine Schlüssel. Dein Gerät.", featuresB: "Heimdguard erzeugt deine Authentifizierungscodes, ohne deine Geheimnisse einem BarbareDestroy-Server anzuvertrauen.", f1t: "Standard-TOTP", f1d: "Kompatibel mit Diensten, die TOTP und otpauth://-Links verwenden.", f2t: "Lokaler verschlüsselter Tresor", f2d: "Geheimnisse werden auf dem Gerät verschlüsselt und durch Android Keystore geschützt.", f3t: "QR-Code oder manuelle Eingabe", f3d: "Scanne den QR-Code des Dienstes oder gib direkt einen Base32-Geheimschlüssel ein.", f4t: "Optionaler PIN", f4d: "Aktiviere auf Wunsch zusätzlichen lokalen Schutz, ohne einen PIN vorzuschreiben.", f5t: "Verschlüsselte Sicherung", f5d: "Erstelle eine lokale Sicherung mit einer Passphrase von mindestens 23 Zeichen und speichere sie dort, wo du möchtest.", f6t: "Keine Datenerfassung", f6d: "Kein Heimdguard-Konto, keine Werbung, keine Reichweitenanalyse und keine entfernte Datenbank deiner Schlüssel.", manifestTitle: "Kein Server kann deine Schlüssel wiederherstellen. Absichtlich.", manifestText: "Heimdguard setzt auf lokale Kontrolle. Geht dein Telefon verloren, kaputt oder wird zurückgesetzt, besitzt BarbareDestroy keine Kopie deines Tresors. Eine verschlüsselte Sicherung durch den Nutzer ist daher unerlässlich.", s1t: "Hinzufügen", s1d: "Scanne den QR-Code oder gib den geheimen Schlüssel deines Dienstes ein.", s2t: "Schützen", s2d: "Aktiviere bei Bedarf einen lokalen PIN und halte dein Telefon gesperrt.", s3t: "Sichern", s3d: "Exportiere eine verschlüsselte Sicherung auf einen Speicher, den du kontrollierst.", available: "Demnächst bei Google Play", downloadTitle: "Heimdguard herunterladen", downloadIntro: "Der Link wird nach Veröffentlichung durch die Heimdguard-Storeseite ersetzt.", android: "Für Android", navHome: "BarbareDestroy Startseite", navPrivacy: "Datenschutz", navTerms: "Nutzungsbedingungen"
    },
    es: {
      eyebrow: "Autenticador local", lead: "Tus códigos de doble autenticación permanecen en una bóveda cifrada de tu teléfono. Sin cuenta Heimdguard, sin nube obligatoria y sin servidor BarbareDestroy.", privacyLine: "Diseñado para funcionar sin conexión: añade por QR o clave secreta, genera TOTP y crea/restaura copias cifradas localmente.", badge1: "Sin conexión", badge2: "Bóveda cifrada", badge3: "Sin publicidad", badge4: "Sin cuenta", storeSoon: "Enlace de la app próximamente", mockLocal: "Local • sin conexión • cifrado", mockAdd: "+ Añadir una clave", featuresA: "Tus claves. Tu dispositivo.", featuresB: "Heimdguard genera tus códigos sin confiar tus secretos a un servidor BarbareDestroy.", f1t: "TOTP estándar", f1d: "Compatible con servicios que utilizan TOTP y enlaces otpauth://.", f2t: "Bóveda local cifrada", f2d: "Los secretos se cifran en el dispositivo y están protegidos por Android Keystore.", f3t: "QR o entrada manual", f3d: "Escanea el QR del servicio o introduce directamente una clave secreta Base32.", f4t: "PIN opcional", f4d: "Añade protección local adicional si quieres, sin hacer obligatorio el PIN.", f5t: "Copia cifrada", f5d: "Crea una copia local protegida por una frase de al menos 23 caracteres y guárdala donde quieras.", f6t: "Sin recopilación", f6d: "Sin cuenta Heimdguard, publicidad, analítica de audiencia ni base remota con tus claves.", manifestTitle: "Ningún servidor puede recuperar tus claves. Es intencional.", manifestText: "Heimdguard prioriza el control local. Si pierdes, rompes o reinicias el teléfono, BarbareDestroy no tiene una copia para restaurar la bóveda. Por eso es esencial crear una copia cifrada.", s1t: "Añade", s1d: "Escanea el QR o introduce la clave secreta facilitada por tu servicio.", s2t: "Protege", s2d: "Activa un PIN local si lo deseas y mantén bloqueado tu teléfono.", s3t: "Guarda", s3d: "Exporta una copia cifrada a un soporte que controles.", available: "Próximamente en Google Play", downloadTitle: "Descargar Heimdguard", downloadIntro: "El enlace se sustituirá por la ficha de Heimdguard cuando se publique.", android: "Para Android", navHome: "Inicio BarbareDestroy", navPrivacy: "Política de privacidad", navTerms: "Condiciones de uso"
    },
    hi: {
      eyebrow: "स्थानीय प्रमाणक", lead: "आपके दो-चरणीय प्रमाणीकरण कोड आपके फ़ोन के एन्क्रिप्टेड वॉल्ट में रहते हैं। Heimdguard खाता, अनिवार्य क्लाउड या BarbareDestroy सर्वर नहीं।", privacyLine: "ऑफ़लाइन उपयोग के लिए बनाया गया: QR कोड या गुप्त कुंजी जोड़ें, TOTP बनाएँ और एन्क्रिप्टेड बैकअप स्थानीय रूप से बहाल करें।", badge1: "ऑफ़लाइन", badge2: "एन्क्रिप्टेड वॉल्ट", badge3: "विज्ञापन रहित", badge4: "बिना खाते", storeSoon: "ऐप लिंक जल्द आएगा", mockLocal: "स्थानीय • ऑफ़लाइन • एन्क्रिप्टेड", mockAdd: "+ कुंजी जोड़ें", featuresA: "आपकी कुंजियाँ। आपका डिवाइस।", featuresB: "Heimdguard आपके रहस्यों को BarbareDestroy सर्वर को दिए बिना प्रमाणीकरण कोड बनाता है।", f1t: "मानक TOTP", f1d: "TOTP और otpauth:// लिंक वाले सेवाओं के साथ संगत।", f2t: "स्थानीय एन्क्रिप्टेड वॉल्ट", f2d: "रहस्य डिवाइस पर एन्क्रिप्ट होते हैं और Android Keystore से सुरक्षित रहते हैं।", f3t: "QR या मैन्युअल प्रविष्टि", f3d: "सेवा का QR स्कैन करें या Base32 गुप्त कुंजी सीधे दर्ज करें।", f4t: "वैकल्पिक PIN", f4d: "चाहें तो अतिरिक्त स्थानीय सुरक्षा जोड़ें; PIN अनिवार्य नहीं है।", f5t: "एन्क्रिप्टेड बैकअप", f5d: "कम से कम 23 अक्षरों की पासफ़्रेज़ से सुरक्षित स्थानीय बैकअप बनाएँ और अपनी पसंद की जगह रखें।", f6t: "कोई संग्रह नहीं", f6d: "Heimdguard खाता, विज्ञापन, ऑडियंस एनालिटिक्स या आपकी कुंजियों का दूरस्थ डेटाबेस नहीं।", manifestTitle: "आपकी कुंजियाँ वापस लाने वाला कोई सर्वर नहीं। यह जानबूझकर है।", manifestText: "Heimdguard स्थानीय नियंत्रण को प्राथमिकता देता है। फ़ोन खोने, टूटने या रीसेट होने पर BarbareDestroy के पास वॉल्ट बहाल करने की कोई कॉपी नहीं होती। इसलिए एन्क्रिप्टेड बैकअप आवश्यक है।", s1t: "जोड़ें", s1d: "QR स्कैन करें या सेवा द्वारा दी गई गुप्त कुंजी दर्ज करें।", s2t: "सुरक्षित करें", s2d: "चाहें तो स्थानीय PIN सक्रिय करें और फ़ोन लॉक रखें।", s3t: "बैकअप", s3d: "एन्क्रिप्टेड बैकअप ऐसे स्टोरेज पर निर्यात करें जिसे आप नियंत्रित करते हैं।", available: "जल्द Google Play पर", downloadTitle: "Heimdguard डाउनलोड करें", downloadIntro: "प्रकाशित होते ही यह लिंक Heimdguard की सूची से बदला जाएगा।", android: "Android के लिए", navHome: "BarbareDestroy होम", navPrivacy: "गोपनीयता नीति", navTerms: "उपयोग की शर्तें"
    },
    in: {
      eyebrow: "Autentikator lokal", lead: "Kode autentikasi dua faktor tetap di brankas terenkripsi pada ponselmu. Tanpa akun Heimdguard, cloud wajib, atau server BarbareDestroy.", privacyLine: "Dirancang untuk bekerja offline: tambah lewat QR atau kunci rahasia, hasilkan TOTP, lalu cadangkan dan pulihkan secara lokal.", badge1: "Offline", badge2: "Brankas terenkripsi", badge3: "Tanpa iklan", badge4: "Tanpa akun", storeSoon: "Tautan aplikasi segera hadir", mockLocal: "Lokal • offline • terenkripsi", mockAdd: "+ Tambah kunci", featuresA: "Kuncimu. Perangkatmu.", featuresB: "Heimdguard membuat kode autentikasi tanpa menyerahkan rahasiamu ke server BarbareDestroy.", f1t: "TOTP standar", f1d: "Kompatibel dengan layanan yang memakai TOTP dan tautan otpauth://.", f2t: "Brankas lokal terenkripsi", f2d: "Rahasia dienkripsi di perangkat dan dilindungi Android Keystore.", f3t: "QR atau input manual", f3d: "Pindai QR dari layanan atau masukkan kunci rahasia Base32 secara langsung.", f4t: "PIN opsional", f4d: "Tambahkan perlindungan lokal jika diinginkan tanpa mewajibkan PIN.", f5t: "Cadangan terenkripsi", f5d: "Buat cadangan lokal dengan frasa sandi minimal 23 karakter dan simpan di lokasi pilihanmu.", f6t: "Tanpa pengumpulan", f6d: "Tanpa akun Heimdguard, iklan, analitik audiens, atau basis data jarak jauh berisi kuncimu.", manifestTitle: "Tidak ada server untuk memulihkan kuncimu. Itu disengaja.", manifestText: "Heimdguard mengutamakan kendali lokal. Jika ponsel hilang, rusak, atau direset, BarbareDestroy tidak memiliki salinan untuk memulihkan brankasmu. Cadangan terenkripsi sangat penting.", s1t: "Tambah", s1d: "Pindai QR atau masukkan kunci rahasia dari layananmu.", s2t: "Lindungi", s2d: "Aktifkan PIN lokal bila diinginkan dan jaga ponsel tetap terkunci.", s3t: "Cadangkan", s3d: "Ekspor cadangan terenkripsi ke penyimpanan yang kamu kendalikan.", available: "Segera di Google Play", downloadTitle: "Unduh Heimdguard", downloadIntro: "Tautan akan diganti dengan halaman Heimdguard saat diterbitkan.", android: "Untuk Android", navHome: "Beranda BarbareDestroy", navPrivacy: "Kebijakan privasi", navTerms: "Ketentuan penggunaan"
    },
    it: {
      eyebrow: "Autenticatore locale", lead: "I tuoi codici di autenticazione a due fattori restano in una cassaforte cifrata sul telefono. Nessun account Heimdguard, cloud obbligatorio o server BarbareDestroy.", privacyLine: "Progettato per funzionare offline: aggiunta tramite QR o chiave segreta, TOTP, backup cifrato e ripristino locale.", badge1: "Offline", badge2: "Cassaforte cifrata", badge3: "Senza pubblicità", badge4: "Senza account", storeSoon: "Link dell'app in arrivo", mockLocal: "Locale • offline • cifrato", mockAdd: "+ Aggiungi chiave", featuresA: "Le tue chiavi. Il tuo dispositivo.", featuresB: "Heimdguard genera i tuoi codici senza affidare i segreti a un server BarbareDestroy.", f1t: "TOTP standard", f1d: "Compatibile con i servizi che usano TOTP e link otpauth://.", f2t: "Cassaforte locale cifrata", f2d: "I segreti sono cifrati sul dispositivo e protetti da Android Keystore.", f3t: "QR o inserimento manuale", f3d: "Scansiona il QR del servizio o inserisci direttamente una chiave segreta Base32.", f4t: "PIN facoltativo", f4d: "Aggiungi una protezione locale extra se vuoi, senza rendere obbligatorio il PIN.", f5t: "Backup cifrato", f5d: "Crea un backup locale protetto da una frase di almeno 23 caratteri e salvalo dove preferisci.", f6t: "Nessuna raccolta", f6d: "Nessun account Heimdguard, pubblicità, analisi del pubblico o database remoto delle tue chiavi.", manifestTitle: "Nessun server può recuperare le tue chiavi. È una scelta.", manifestText: "Heimdguard privilegia il controllo locale. Se il telefono viene perso, rotto o ripristinato, BarbareDestroy non possiede copie per ripristinare la cassaforte. Un backup cifrato è quindi essenziale.", s1t: "Aggiungi", s1d: "Scansiona il QR o inserisci la chiave segreta fornita dal servizio.", s2t: "Proteggi", s2d: "Attiva un PIN locale se vuoi e mantieni il telefono bloccato.", s3t: "Salva", s3d: "Esporta un backup cifrato su un supporto sotto il tuo controllo.", available: "Presto su Google Play", downloadTitle: "Scarica Heimdguard", downloadIntro: "Il link verrà sostituito dalla pagina Heimdguard appena pubblicata.", android: "Per Android", navHome: "Home BarbareDestroy", navPrivacy: "Informativa sulla privacy", navTerms: "Condizioni d'uso"
    },
    ja: {
      eyebrow: "ローカル認証アプリ", lead: "2段階認証コードはスマートフォン内の暗号化保管庫に保存されます。Heimdguardアカウント、必須クラウド、BarbareDestroyサーバーは不要です。", privacyLine: "オフライン動作を前提に設計：QRコードまたは秘密鍵の追加、TOTP生成、暗号化バックアップとローカル復元。", badge1: "オフライン", badge2: "暗号化保管庫", badge3: "広告なし", badge4: "アカウント不要", storeSoon: "アプリリンクは近日公開", mockLocal: "ローカル • オフライン • 暗号化", mockAdd: "+ キーを追加", featuresA: "あなたのキー。あなたの端末。", featuresB: "Heimdguardは秘密情報をBarbareDestroyサーバーへ預けずに認証コードを生成します。", f1t: "標準TOTP", f1d: "TOTP規格とotpauth://リンクを使用するサービスに対応。", f2t: "ローカル暗号化保管庫", f2d: "秘密情報は端末上で暗号化され、Android Keystoreで保護されます。", f3t: "QRまたは手動入力", f3d: "サービスのQRコードを読み取るか、Base32秘密鍵を直接入力します。", f4t: "任意のPIN", f4d: "必要な場合だけ追加のローカル保護を有効にでき、PINは必須ではありません。", f5t: "暗号化バックアップ", f5d: "23文字以上のパスフレーズで保護したローカルバックアップを作成し、好きな場所に保管できます。", f6t: "収集なし", f6d: "Heimdguardアカウント、広告、利用分析、キーのリモートデータベースはありません。", manifestTitle: "キーを復元するサーバーはありません。意図した設計です。", manifestText: "Heimdguardはローカル管理を優先します。端末の紛失・故障・初期化時、BarbareDestroyには保管庫を復元するコピーがありません。そのため暗号化バックアップが重要です。", s1t: "追加", s1d: "QRを読み取るか、サービスから提供された秘密鍵を入力します。", s2t: "保護", s2d: "必要ならローカルPINを有効にし、端末自体もロックしてください。", s3t: "バックアップ", s3d: "管理できる保存先へ暗号化バックアップを書き出します。", available: "Google Playで近日公開", downloadTitle: "Heimdguardをダウンロード", downloadIntro: "公開後、このリンクをHeimdguardのストアページに置き換えます。", android: "Android向け", navHome: "BarbareDestroyホーム", navPrivacy: "プライバシーポリシー", navTerms: "利用規約"
    },
    pt: {
      eyebrow: "Autenticador local", lead: "Os teus códigos de autenticação de dois fatores ficam num cofre cifrado no telemóvel. Sem conta Heimdguard, cloud obrigatória ou servidor BarbareDestroy.", privacyLine: "Criado para funcionar offline: adiciona por QR ou chave secreta, gera TOTP e faz/restaura cópias cifradas localmente.", badge1: "Offline", badge2: "Cofre cifrado", badge3: "Sem publicidade", badge4: "Sem conta", storeSoon: "Ligação da aplicação em breve", mockLocal: "Local • offline • cifrado", mockAdd: "+ Adicionar chave", featuresA: "As tuas chaves. O teu dispositivo.", featuresB: "Heimdguard gera os teus códigos sem confiar os segredos a um servidor BarbareDestroy.", f1t: "TOTP padrão", f1d: "Compatível com serviços que utilizam TOTP e ligações otpauth://.", f2t: "Cofre local cifrado", f2d: "Os segredos são cifrados no dispositivo e protegidos pelo Android Keystore.", f3t: "QR ou introdução manual", f3d: "Digitaliza o QR do serviço ou introduz diretamente uma chave secreta Base32.", f4t: "PIN opcional", f4d: "Adiciona proteção local extra se quiseres, sem tornar o PIN obrigatório.", f5t: "Cópia cifrada", f5d: "Cria uma cópia local protegida por uma frase de pelo menos 23 caracteres e guarda-a onde quiseres.", f6t: "Sem recolha", f6d: "Sem conta Heimdguard, publicidade, análise de audiência ou base remota com as tuas chaves.", manifestTitle: "Nenhum servidor pode recuperar as tuas chaves. É intencional.", manifestText: "Heimdguard privilegia o controlo local. Se o telemóvel for perdido, avariado ou reposto, BarbareDestroy não tem qualquer cópia para restaurar o cofre. Uma cópia cifrada é, por isso, essencial.", s1t: "Adicionar", s1d: "Digitaliza o QR ou introduz a chave secreta fornecida pelo serviço.", s2t: "Proteger", s2d: "Ativa um PIN local se quiseres e mantém o telemóvel bloqueado.", s3t: "Guardar", s3d: "Exporta uma cópia cifrada para um suporte que controlas.", available: "Em breve no Google Play", downloadTitle: "Transferir Heimdguard", downloadIntro: "A ligação será substituída pela página Heimdguard quando for publicada.", android: "Para Android", navHome: "Início BarbareDestroy", navPrivacy: "Política de privacidade", navTerms: "Termos de utilização"
    },
    ru: {
      eyebrow: "Локальный аутентификатор", lead: "Коды двухфакторной аутентификации хранятся в зашифрованном сейфе на телефоне. Без аккаунта Heimdguard, обязательного облака и сервера BarbareDestroy.", privacyLine: "Создан для работы офлайн: добавление по QR или секретному ключу, генерация TOTP, зашифрованное резервное копирование и локальное восстановление.", badge1: "Офлайн", badge2: "Зашифрованный сейф", badge3: "Без рекламы", badge4: "Без аккаунта", storeSoon: "Ссылка на приложение скоро", mockLocal: "Локально • офлайн • зашифровано", mockAdd: "+ Добавить ключ", featuresA: "Твои ключи. Твоё устройство.", featuresB: "Heimdguard генерирует коды, не передавая секреты на сервер BarbareDestroy.", f1t: "Стандарт TOTP", f1d: "Совместим с сервисами, использующими TOTP и ссылки otpauth://.", f2t: "Локальный зашифрованный сейф", f2d: "Секреты шифруются на устройстве и защищаются Android Keystore.", f3t: "QR или ручной ввод", f3d: "Сканируй QR сервиса или введи секретный ключ Base32 вручную.", f4t: "Необязательный PIN", f4d: "При желании добавь дополнительную локальную защиту; PIN не обязателен.", f5t: "Зашифрованная копия", f5d: "Создай локальную копию с парольной фразой минимум из 23 символов и храни её там, где выберешь.", f6t: "Без сбора данных", f6d: "Нет аккаунта Heimdguard, рекламы, аналитики аудитории и удалённой базы твоих ключей.", manifestTitle: "Сервера для восстановления ключей нет. Так задумано.", manifestText: "Heimdguard ставит локальный контроль на первое место. При потере, поломке или сбросе телефона у BarbareDestroy нет копии сейфа. Поэтому зашифрованная резервная копия необходима.", s1t: "Добавь", s1d: "Сканируй QR или введи секретный ключ сервиса.", s2t: "Защити", s2d: "При желании включи локальный PIN и блокируй телефон.", s3t: "Сохрани", s3d: "Экспортируй зашифрованную копию на носитель под твоим контролем.", available: "Скоро в Google Play", downloadTitle: "Скачать Heimdguard", downloadIntro: "После публикации ссылка будет заменена на страницу Heimdguard.", android: "Для Android", navHome: "Главная BarbareDestroy", navPrivacy: "Политика конфиденциальности", navTerms: "Условия использования"
    },
    ur: {
      eyebrow: "مقامی تصدیق کار", lead: "آپ کے دو مرحلہ تصدیقی کوڈ فون کے خفیہ والٹ میں رہتے ہیں۔ Heimdguard اکاؤنٹ، لازمی کلاؤڈ یا BarbareDestroy سرور کی ضرورت نہیں۔", privacyLine: "آف لائن کام کے لیے بنایا گیا: QR یا خفیہ کلید شامل کریں، TOTP بنائیں، خفیہ بیک اپ اور مقامی بحالی کریں۔", badge1: "آف لائن", badge2: "خفیہ والٹ", badge3: "بغیر اشتہار", badge4: "بغیر اکاؤنٹ", storeSoon: "ایپ کا لنک جلد آئے گا", mockLocal: "مقامی • آف لائن • خفیہ", mockAdd: "+ کلید شامل کریں", featuresA: "آپ کی کلیدیں۔ آپ کا آلہ۔", featuresB: "Heimdguard آپ کے راز BarbareDestroy سرور کے حوالے کیے بغیر تصدیقی کوڈ بناتا ہے۔", f1t: "معیاری TOTP", f1d: "TOTP اور otpauth:// لنکس استعمال کرنے والی خدمات کے ساتھ مطابقت رکھتا ہے۔", f2t: "مقامی خفیہ والٹ", f2d: "راز آلے پر خفیہ کیے جاتے ہیں اور Android Keystore سے محفوظ رہتے ہیں۔", f3t: "QR یا دستی اندراج", f3d: "سروس کا QR اسکین کریں یا Base32 خفیہ کلید براہ راست درج کریں۔", f4t: "اختیاری PIN", f4d: "چاہیں تو اضافی مقامی حفاظت فعال کریں؛ PIN لازمی نہیں۔", f5t: "خفیہ بیک اپ", f5d: "کم از کم 23 حروف کی پاس فریز سے محفوظ مقامی بیک اپ بنائیں اور اپنی پسند کی جگہ رکھیں۔", f6t: "کوئی ڈیٹا جمع نہیں", f6d: "Heimdguard اکاؤنٹ، اشتہار، آڈینس اینالیٹکس یا کلیدوں کا ریموٹ ڈیٹابیس نہیں۔", manifestTitle: "کلیدیں واپس لانے والا کوئی سرور نہیں۔ یہ جان بوجھ کر ہے۔", manifestText: "Heimdguard مقامی کنٹرول کو ترجیح دیتا ہے۔ فون گم، خراب یا ری سیٹ ہونے پر BarbareDestroy کے پاس والٹ بحال کرنے کی کوئی نقل نہیں ہوتی۔ اس لیے خفیہ بیک اپ ضروری ہے۔", s1t: "شامل کریں", s1d: "QR اسکین کریں یا سروس کی دی ہوئی خفیہ کلید درج کریں۔", s2t: "محفوظ کریں", s2d: "چاہیں تو مقامی PIN فعال کریں اور فون لاک رکھیں۔", s3t: "بیک اپ", s3d: "خفیہ بیک اپ ایسی جگہ برآمد کریں جو آپ کے کنٹرول میں ہو۔", available: "جلد Google Play پر", downloadTitle: "Heimdguard ڈاؤن لوڈ کریں", downloadIntro: "شائع ہونے پر یہ لنک Heimdguard کی اسٹور فہرست سے بدل دیا جائے گا۔", android: "Android کے لیے", navHome: "BarbareDestroy ہوم", navPrivacy: "رازداری پالیسی", navTerms: "استعمال کی شرائط"
    },
    zh: {
      eyebrow: "本地身份验证器", lead: "双重验证代码保存在手机上的本地加密保险库中。无需 Heimdguard 账号、强制云端或 BarbareDestroy 服务器。", privacyLine: "专为离线工作设计：通过二维码或密钥添加，生成 TOTP，并进行本地加密备份与恢复。", badge1: "离线", badge2: "加密保险库", badge3: "无广告", badge4: "无需账号", storeSoon: "应用链接即将上线", mockLocal: "本地 • 离线 • 加密", mockAdd: "+ 添加密钥", featuresA: "你的密钥。你的设备。", featuresB: "Heimdguard 在不把密钥交给 BarbareDestroy 服务器的情况下生成身份验证代码。", f1t: "标准 TOTP", f1d: "兼容使用 TOTP 标准和 otpauth:// 链接的服务。", f2t: "本地加密保险库", f2d: "密钥在设备上加密，并由 Android Keystore 保护。", f3t: "二维码或手动输入", f3d: "扫描服务提供的二维码，或直接输入 Base32 密钥。", f4t: "可选 PIN", f4d: "需要时可增加本地保护，但 PIN 并非强制。", f5t: "加密备份", f5d: "创建由至少 23 个字符口令保护的本地备份，并保存到你选择的位置。", f6t: "不收集数据", f6d: "无 Heimdguard 账号、无广告、无受众分析，也没有存储你密钥的远程数据库。", manifestTitle: "没有服务器能够恢复你的密钥。这是刻意的设计。", manifestText: "Heimdguard 优先保证本地掌控。手机丢失、损坏或重置时，BarbareDestroy 没有可用于恢复保险库的副本，因此加密备份非常重要。", s1t: "添加", s1d: "扫描二维码或输入服务提供的密钥。", s2t: "保护", s2d: "需要时启用本地 PIN，并保持手机锁定。", s3t: "备份", s3d: "将加密备份导出到你自己控制的存储位置。", available: "即将登陆 Google Play", downloadTitle: "下载 Heimdguard", downloadIntro: "发布后，此链接将替换为 Heimdguard 的商店页面。", android: "Android 版", navHome: "BarbareDestroy 首页", navPrivacy: "隐私政策", navTerms: "使用条款"
    }
  };

  function normalizeLang(value) {
    const raw = String(value || '').toLowerCase().replace('_', '-');
    const base = raw.split('-')[0];
    if (base === 'id') return 'in';
    return I18N[base] ? base : 'fr';
  }

  function applyLang(lang) {
    lang = normalizeLang(lang);
    const selected = I18N[lang] || I18N.fr;
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      const key = el.getAttribute('data-i18n');
      const value = selected[key] !== undefined ? selected[key] : I18N.fr[key];
      if (value !== undefined) el.textContent = value;
    });
    document.documentElement.lang = lang === 'in' ? 'id' : lang;
    document.documentElement.dir = lang === 'ur' ? 'rtl' : 'ltr';
    try { localStorage.setItem('heimdguard-site-lang', lang); } catch (_) {}
    window.dispatchEvent(new CustomEvent('heimdguard-language-changed', { detail: { lang: lang } }));
  }

  function initialLang() {
    let saved = '';
    try { saved = localStorage.getItem('heimdguard-site-lang') || ''; } catch (_) {}
    return normalizeLang(saved || navigator.language || 'fr');
  }

  window.HG_I18N = I18N;
  window.hgApplyLang = applyLang;

  document.addEventListener('DOMContentLoaded', function () {
    applyLang(initialLang());
    document.querySelectorAll('[data-lang]').forEach(function (button) {
      button.addEventListener('click', function () { applyLang(button.getAttribute('data-lang')); });
    });
  });
})();
